type DatasetEntry = {
    favoriteColor: string, gender: string, animal: string
}

const dataset: DatasetEntry[] = [
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "female", animal: "cat" },
    { favoriteColor: "none", gender: "male", animal: "none" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "dog" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "red", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "male", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "none" },
    { favoriteColor: "yellow", gender: "male", animal: "none" },
    { favoriteColor: "red", gender: "male", animal: "dog" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "pink", gender: "male", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "cat" },
    { favoriteColor: "pink", gender: "male", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "dog" },
    { favoriteColor: "yellow", gender: "female", animal: "none" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "yellow", gender: "male", animal: "dog" },
    { favoriteColor: "green", gender: "female", animal: "none" },
    { favoriteColor: "none", gender: "female", animal: "cat" },
    { favoriteColor: "green", gender: "female", animal: "cat" },
    { favoriteColor: "red", gender: "male", animal: "cat" },
    { favoriteColor: "green", gender: "male", animal: "cat" },
    { favoriteColor: "blue", gender: "female", animal: "none" },
    { favoriteColor: "pink", gender: "female", animal: "dog" },
];

function pipe(...fns) {
    return function (res) {
        return fns.reduce((acc, next) => next(acc), res);
    }
}

function splitBy<T>(cond: (value: T) => boolean) {
    return function (xs: T[]) {
        return xs.reduce<{
            left: T[],
            right: T[]
        }>(
            (acc, cur) => cond(cur)
                ? {
                    ...acc,
                    left: [...acc.left, cur],
                }
                : {
                    ...acc,
                    right: [...acc.right, cur],
                }
            ,
            {
                left: [],
                right: [],
            }
        );
    }
}

function counts(key) {
    return function (xs) {
        return {
            counts: xs.reduce((acc, cur) => {
                if (!acc[cur[key]]) {
                    acc[cur[key]] = 0;
                }

                acc[cur[key]] = acc[cur[key]] + 1;

                return acc;
            }, {}),
            total: xs.length,
        }
    }
}

function relativeCounts({ counts, total }) {
    return Object.entries(counts).reduce(
        (acc, [key, count]) => ({
            ...acc,
            [key]: count / total,
        }),
        {}
    );
}

function map<T, U>(f: (value: T) => U): (xs: T[]) => U[] {
    return function (xs: T[]) { return xs.map(f); }
}
function filter<T>(p: (value: T) => boolean): (xs: T[]) => T[] {
    return function (xs) { return xs.filter(p); }
}

function sum(xs: number[]): () => number {
    return function () {
        return xs.reduce((acc, cur) => acc + cur, 0);
    }
}

function log<T>(x: T): T {
    console.log(x);
    return x;
};

function tap<T>(f: (value: T) => void): (value: T) => T {
    return function (x) {
        f(x);
        return x;
    }
}


function apply<T, U>(f: (value: T) => U) {
    return function (xs: T | T[]): U | U[] {
        if (Array.isArray(xs)) return xs.map(f);
        return f(xs);
    }
}

console.log(pipe(counts("gender"))(dataset));
console.log(
    pipe(
        counts("animal")
        // log
    )(dataset)
);
console.log(
    pipe(
        counts("favoriteColor"),
        // log,
        relativeCounts
    )(dataset)
);

console.log(
    pipe(
        splitBy<DatasetEntry>((entry) => entry.gender === "male"),
        apply(({ left, right }) => ({
            male: pipe(counts("favoriteColor"), relativeCounts)(left),
            female: pipe(counts("favoriteColor"), relativeCounts)(right),
        }))
        // apply(({male, female}) => ({
        //	male: sum(Object.values(male)),
        //	female: sum(Object.values(female)),
        // }))
    )(dataset)
);
